SET SERVEROUTPUT ON
DECLARE

	VEMP EMP%ROWTYPE; 
	ANNSAL NUMBER(7,2);
BEGIN
	DBMS_OUTPUT.PUT_LINE('사번 / 이름 / 연봉'); 
	DBMS_OUTPUT.PUT_LINE('-------------------------');

	SELECT * INTO VEMP
	FROM EMP
	WHERE ENAME='SCOTT';

	IF(VEMP.COMM IS NULL) THEN VEMP.COMM := 0;
	END IF;

	ANNSAL:=VEMP.SAL*12+VEMP.COMM; 

	DBMS_OUTPUT.PUT_LINE(VEMP.EMPNO || ' /' || VEMP.ENAME || ' /' || ANNSAL); 
END;
/


