SET SERVEROUTPUT ON
DECLARE
--타입정의
  TYPE  ENAME_TABLE_TYPE IS TABLE OF EMP.ENAME%TYPE
    INDEX BY BINARY_INTEGER;
  TYPE  JOB_TABLE_TYPE IS TABLE OF EMP.JOB%TYPE
    INDEX BY BINARY_INTEGER;

--선언
  ENAME_TABLE  ENAME_TABLE_TYPE;
  JOB_TABLE  JOB_TABLE_TYPE;
  
  I BINARY_INTEGER := 0;

BEGIN  

  FOR  K IN (SELECT ENAME, JOB FROM EMP) LOOP
    I := I + 1;              
    ENAME_TABLE(I) := K.ENAME;
    JOB_TABLE(I) := K.JOB;     
  END LOOP;

  FOR J IN 1..I LOOP          
    DBMS_OUTPUT.PUT_LINE(RPAD(ENAME_TABLE(J),12)  || ' / ' ||  RPAD(JOB_TABLE(J),9));
  END LOOP;
END;
/
